name: aldi_m_alpaujan_mobile_front_end
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # state management
  get: ^4.6.6

  # localization
  flutter_localization: ^0.3.3
  flutter_localizations:
    sdk: flutter


  # intl
  intl: ^0.20.2

  # http client
  dio: ^5.7.0

  # Network client generator
  retrofit: ^4.4.1

  # logger
  logger: ^2.5.0

  # Model Helper
  json_annotation: ^4.9.0

  # http parser
  http_parser: ^4.0.2

  # file picker
  image_picker: ^1.1.2

  # firebase
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2

  # notification
  flutter_local_notifications: ^19.4.2

  # in app package
  in_app_update: ^4.2.3

  # icons
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296

  # web view
  webview_flutter: ^4.10.0

  # markdown
  flutter_markdown: ^0.7.4+2

  # splash screen
  flutter_native_splash: ^2.4.3

  # loading
  shimmer: ^3.0.0

  # launcher
  url_launcher: ^6.3.1
  
  # spelling
  spelling_number: ^0.0.4

  # refresher
  pull_to_refresh: ^2.0.0

  # date picker
  syncfusion_flutter_datepicker: ^31.1.19

  # local storage & database
  shared_preferences: ^2.3.3

  # currency format
  currency_text_input_formatter: ^2.2.6

  # carousel
  carousel_slider: ^5.0.0

  # file/folder helper
  mime: ^2.0.0
  path: ^1.9.0
  path_provider: ^2.1.5

  # viewer
  easy_image_viewer: ^1.5.1
  flutter_pdfview: ^1.3.4

  # share 
  share_plus: ^12.0.0

  # handler
  permission_handler: ^12.0.1

  # encryption
  crypto: ^3.0.6

  # svg
  flutter_svg: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  retrofit_generator: ^10.0.6  
  json_serializable: ^6.9.0

  # lints
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/fonts/
    - assets/html/
    - assets/illustration/
    - assets/image/
    - assets/svg/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunito/Nunito-ExtraBold.ttf
          weight: 800